name: CI - backend

on:
  pull_request:
    branches:
      - "backend"
    paths:
      - 'src/main/java/com/danilkompaniets/**'
      - 'src/test/java/com/danilkompaniets/**'
      - 'src/main/resources/**'
      - 'pom.xml'
      - 'docker-compose.yaml'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: danilkompaniets
          POSTGRES_PASSWORD: Danone0502603734!
          POSTGRES_DB: customer

        ports:
          - 5332:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build and run ITs with maven
        run: mvn clean verify

        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

